# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kw_rcpp <- function(mtr, group) {
    .Call('pmartRmems_kw_rcpp', PACKAGE = 'pmartRmems', mtr, group)
}

nonmissing_per_grp <- function(mtr, group) {
    .Call('pmartRmems_nonmissing_per_grp', PACKAGE = 'pmartRmems', mtr, group)
}

pooled_cv_rcpp <- function(mtr, group) {
    .Call('pmartRmems_pooled_cv_rcpp', PACKAGE = 'pmartRmems', mtr, group)
}

#' @export
rcpp_hello_world <- function() {
    .Call('pmartRmems_rcpp_hello_world', PACKAGE = 'pmartRmems')
}

